spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.197.128/sell?characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
